[package]
name = "raven-gui"
description = "Raven's administration window"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
raven = { path = "../raven" }
colony-ui = "0.1.4"
iced = { version = "0.14.0", features = ["tokio", "advanced"] }
tokio = { version = "1", features = ["rt"] }
