[package]
name = "raven-gui"
description = "Raven's administration window"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
raven.workspace = true
colony-ui.workspace = true
iced = { workspace = true, features = ["tokio", "advanced"] }
tokio = { workspace = true, features = ["rt"] }
