[package]
name = "raven"
description = "Run Windows programs on Linux against a real Windows installation mounted as C:"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.6", features = ["derive"] }
nt-hive = "0.3.0"
rustix = { version = "1.1.4", features = ["mount", "thread", "process", "fs"] }
serde = { version = "1.0.229", features = ["derive"] }
thiserror = "2.0.20"
toml = "1.1.4"

[dev-dependencies]
regf = "0.1.0"
